title:        "Wang, Xinyue"
tagline:      "Doctoral Candidate in Economics"
description:  "Personal academic website of Xinyue Wang."
author:       "Xinyue Wang"
email:        "xinyue.wang@wiso.uni-koeln.de"

url:          "https://xinyuewang123.github.io"
baseurl:      ""

markdown:     kramdown
permalink:    pretty
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

nav:
  - title: About
    url:   /
  - title: Research
    url:   /research/
  - title: CV
    url:   /cv/
